sequenceDiagram
    participant ClientNode as ClientNode (nodeA)
    participant Client as vipnode client
    participant Pool as vipnode pool
    participant Host as vipnode host
    participant HostNode as HostNode (nodeB)
    Host->>Pool: vipnode_host(nodeB)
    loop Keepalive
        HostNode--xPool: vipnode_update(peers, nodeInfo) 
    end
    Client->>Pool: vipnode_client(nodeA)
    Pool--xHost: whitelist(nodeA)
    Host->HostNode: admin_addTrustedPeer(nodeA)
    Host--xPool: 👍
    Pool->>Client: {"nodes": [nodeB]}
    Client->ClientNode: admin_addTrustedPeer(nodeB)
    ClientNode->HostNode: 👋 👋
    loop Keepalive
        ClientNode--xPool: vipnode_update(peers, nodeInfo) 
    end
