sequenceDiagram
    participant ClientNode as ClientNode (nodeA)
    participant Client as vipnode client
    participant Pool as vipnode pool
    participant Host as vipnode host
    participant HostNode as HostNode (nodeB)
    Client->>Pool: vipnode_connect(nodeA)
    Pool--xHost: whitelist(nodeA)
    Host->HostNode: admin_addTrustedPeer(nodeA)
    Host--xPool: :+1:
    Pool->>Client: {"nodes": [nodeB]}
    Client->ClientNode: admin_addTrustedPeer(nodeB)
    ClientNode->HostNode: :wave:
